###########################################################
#
#   iCloud3 Configuration Parameters
#
#   These parameters will override those specified in the HA
#   configuration.yaml file. They can be used to change the
#   iCloud3 operations without restarting HA. To do this,
#   change the parameter in this file and select 
#   Event Log > Actions > Restart iC3
#
###########################################################

# --Track Devices Parameters-------------------------------
#devices:
#  - device_name: gary_iphone
#    name: Gary
#    email: gary_456@email.com
#    picture: gary.png
#  - device_name: lillian_iphone
#    name: Lillian
#    email: lillian_789@email.com
#    picture: lillian.png

# Other devices parameters not normally used
#    noiosapp: false
#    iosapp_suffix: _app
#    iosapp_entity: gary_iphone_app
#    track_from_zone: warehouse

#event_log_card_directory: 'www/custom_cards'

# --Zone/Tracking Parameters--------------------------------
#inzone_interval: '60 min'
#max_interval: '4 hrs'
#center_in_zone: true
#stationary_inzone_interval: '30 min'
#stationary_still_time: '8 min'
#stationary_zone_offset: 1, 0
#travel_time_factor: .6
#distance_method: waze

# --Display Parameters--------------------------------------
#display_zone_fname: True
#unit_of_measurement: mi
#time_format: 24
#display_text_as:
#  - gary-icloud-acct@gmail.com > gary-email@email.com
#  - lillian-icloud-acct@gmail.com > lillian-email@email.com

# --Accuracy Parameters-------------------------------------
#gps_accuracy_threshold: 100
#ignore_gps_accuracy_inzone: True
#old_location_threshold: '3 min'

# --Waze Parameters-----------------------------------------
#distance_method: waze
#waze_region: US
#waze_min_distance: 1
#waze_max_distance: 9999
#waze_realtime: False

# -- Debug/Logging Parameters-------------------------------
#log_level: debug
#log_level: debug+intervalcalc
#log_level: debug+rawdata
