title: Automationer
id: automationer
icon: mdi:settings
background: center / cover no-repeat url('/local/habakgrounds.jpg')
cards:
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: 'On'
    filter:
      include:
        - entity_id: "automation.*"
          state: "on"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: 'Off'
    filter:
      include:
        - entity_id: "automation.*"
          state: "off"