id: 'okej_event_command'
alias: 'okej_event_command'
trigger:
- platform: event # this is the command
  event_type: telegram_callback
  event_data:
    command: '/okej_event'
action:
- service: telegram_bot.send_message # Sends message to group that "person" opens the door
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    target: -1001200237113
    parse_mode: markdown
    message: '*{{ trigger.event.data["from_first"] }}* har läst och vet om detta nu. Mer info: https://kernehed.duckdns.org:8123/calendar'
- service: telegram_bot.edit_replymarkup
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: -1001200237113
    inline_keyboard: 