id: 'turn_off_sova_i_kallaren_command'
alias: 'turn_off_sova_i_kallaren_command'
trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    command: '/turn_off_sova_i_kallaren'
action:
- service: input_boolean.turn_off
  data:
    entity_id:
      - input_boolean.sovdags_i_kallaren
- service: automation.turn_on
  data:
    entity_id:
      - automation.tand_kallare_lamporna_nar_rorelse_i_kallaren
- service: telegram_bot.send_message
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    target: -1001200237113
    parse_mode: markdown
    message: 'Okej, *{{ trigger.event.data["from_first"] }}* har nu stängt av sova-i-källaren läget.'
- service: telegram_bot.edit_replymarkup
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: -1001200237113
    inline_keyboard: 
