id: turn_off_electricity
alias: 'turn_off_electricity'
trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    command: '/turn_off_electricity'
action:
- service: automation.turn_off
  entity_id:
  - automation.tand_altanbelysningen_vid_rorelse
  - automation.tand_badrumsbelysningen_vid_rorelse
  - automation.tand_bankbelysningen_nar_rorelse
  - automation.tand_kallare_lamporna_nar_rorelse_i_kallaren
  - automation.tand_skafferiet_lampan_nar_rorelse_i_skafferiet
  - automation.tand_tvattstuge_lamporna_nar_rorelse
- service: light.turn_off
  entity_id: all
- service: telegram_bot.send_message
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    target: -1001200237113
    parse_mode: markdown
    message: 'Okej, *{{ trigger.event.data["from_first"] }}* har stängt av vissa automationer och alla lampor.'
- service: telegram_bot.edit_replymarkup
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: -1001200237113
    inline_keyboard: 