#########################################################
#
#   AUTOMATIONS_OLD
#   ---------------
#
#   GARAGE DOOR AUTOMATIONS
#
#########################################################


#--------------------------------------------------------------
#   If the Garage Door is open after 8pm, close it
#--------------------------------------------------------------
- alias: Close Garage Door (Open after 8pm)
  id: close_garage_door_after_8pm
  trigger:
    platform: time
    at: '20:00:00'
    
  condition:
    condition: state
    entity_id: sensor.garage_door
    state: 'Open'
    
  action:
    - service: switch.turn_on
      entity_id: switch.garage_door
      
    - service: script.notify_gary_iphone
      data:
        title: Garage Door Closed
        message: After 8pm - Close Door Automation Triggered

#--------------------------------------------------------------
#   If the Garage Door is open and no one is home, close it
#--------------------------------------------------------------
- alias: Close Garage Door (No One Home)
  id: close_garage_door_no_one_home
  trigger:
    platform: state
    entity_id: sensor.someone_home_flag
    to: 'all away'
    
  condition:
    condition: state
    entity_id: sensor.garage_door
    state: 'Open'
    
  action:
    - service: switch.turn_on
      entity_id: switch.garage_door
      
    - service: script.notify_gary_iphone
      data:
        title: Garage Door Closed
        message: No One Home - Close Door Automation Triggered
