# yamllint disable rule:document-start

#########################################################
#
#   IPHONE/ICLOUD SELECTION AUTOMATIONS
#
#########################################################

- alias: Set Gary iPhone Interval
  id: set_gary_iphone_interval
  trigger:
    - platform: state
      entity_id: input_select.icloud_set_interval
  action:
    - service: device_tracker.icloud_set_interval
      data_template:
        account_name: gary_icloud
        device_name: gary_iphone
        interval: '{{ states("input_select.icloud_set_interval") }}'

- alias: iCloud Command
  id: icloud_command
  trigger:
    - platform: state
      entity_id: input_select.icloud_commands
  action:
    - service: device_tracker.icloud_update
      data_template:
        account_name: gary_icloud
        command: '{{ states("input_select.icloud_commands") }}'

- alias: iCloud Debug Command
  id: icloud_debug_command
  trigger:
    - platform: state
      entity_id: input_select.icloud_debug_commands
  action:
    - service: device_tracker.icloud_update
      data_template:
        account_name: gary_icloud
        command: '{{ states("input_select.icloud_debug_commands") }}'
