# yamllint disable rule:document-start

#########################################################
#
#   GARAGE DOOR ZWAVE SWITCH VIA SMARTTHINGS
#
#########################################################

# ---- Garage Door Z-Wave switch ------------------------

- platform: template
  covers:
    garage_door:
      open_cover:
        # service: script.show_garage_door_status
        service: switch.turn_on
        data:
          entity_id: switch.garage_door
      close_cover:
        # service: script.show_garage_door_status
        service: switch.turn_on
        data:
          entity_id: switch.garage_door
