# yamllint disable rule:document-start

#########################################################
#
#   DEVICE_TRACKERS
#
#########################################################

# ----  iCloud iPhone Location Services ------------------------
- platform: icloud3
  username: !secret gary_icloud_username
  password: !secret gary_icloud_password
  # tracking_method: famshr
  tracking_method: fmf
  # tracking_method: iosapp

  config_ic3_file_name: config_ic3.yaml
  exclude_sensors: batstat,zon2,zon3,lzon2,lzon3

  # track_devices:
  #   - gary_iphone > gcobb-icloud@email.com, gary.png
  #   - lillian_iphone > lillian-icloud@email.com, lillian.png

  # stationary_still_time: '5 min'
  # stationary_inzone_interval: '15 min'
  # inzone_interval: '30 min'
  # log_level: debug
  # log_level: debug+intervalcalc
  # log_level: debug+rawdata
  # center_in_zone: False
  # display_text_as:
  #   - gary-icloud@gmail.com > gary-secret@email.com
  #   - lillian-icloud@gmail.com > lillian-secret@email.com

# ----- Other Configuration Variables (set to default values) ---
#  group: primary
#  gps_accuracy_threshold: 175
#  tracking_method: fmf
#  stationary_still_time: '2 min'
#  stationary_inzone_interval: '10 min'
#  inzone_interval: '30 min'
#  tracking_method: iosapp
#  inzone_interval: '2 hrs'
#  max_interval: '30 min'
#  stationary_inzone_interval: '30 min'
#  stationary_still_time: '8 min'
#  gps_accuracy_threshold: 200
#  old_location_threshold: '3 min'
#  ignore_gps_accuracy_inzone: False
#  travel_time_factor: .6
#  hide_gps_coordinates: false
#  distance_method: calc
#  waze_region: EU
#  waze_min_distance: 1
#  waze_max_distance: 9999
#  waze_realtime: False
#  entity_registry_file_name: '/config/.storage/core.entity_registry'
