# yamllint disable rule:document-start

#########################################################
#
#   BADGE TEMPLATE SENSORS
#
#########################################################

# -- Gary/Lillian location badge --------------------
- platform: template
  sensors:
    gary_badge:
      friendly_name: Gary
      value_template: '{{states("sensor.gary_iphone_badge")}}'
      entity_picture_template: /local/gary.png
