#########################################################
#
#   GARAGE DOOR ZWAVE SWITCH VIA SMARTTHINGS
#
#########################################################

#---- Garage Door Z-Wave switch ----------------------------
- platform: mqtt
  name: "garage_door"
  state_topic: "smartthings/Garage Door/switch/state"
  command_topic: "smartthings/Garage Door/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  retain: false
         
          