alias: gastlage
initial_state: 'on'
id: '15459257587003213'
trigger:
  platform: state
  entity_id: input_boolean.guest_mode
  from: 'on'
  to: 'off'
action:
  - service: automation.turn_on
    entity_id: automation.away_mode
  - service: tts.google_translate_say
    entity_id: media_player.tts
    data:
      message: "Gästläget har inaktiverats, sätter på de funktioner ni inte kan leva utan. Äntligen är jag tillbaka!"
