homeassistant:
#  packages: !include_dir_named packages
  # Name of the location where Home Assistant is running
  name: Hem
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# EXTERNAL DIRS
  whitelist_external_dirs:
  - /config/snapshot

####CLOUD
cloud:

#LOVELACE
lovelace:
  mode: yaml

# CUSTOM UPDATER
custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json

#Media extractor
media_extractor:

#Panel iframe
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret panel_configurator
  tautulli:
    title: Tautulli
    icon: mdi:filmstrip
    url: !secret tautulli_configurator
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: !secret pihole_configurator
# DARKSKY
weather:
  - platform: darksky
    api_key: !secret darksky_weather

# Map
map: 

# Enables the frontend
frontend:
    themes: !include themes.yaml # your themes go in this file, or directly below here
    javascript_version: latest

 # Enables configuration UI
config:

# Recorder, the DB. Purge db every 3 days.
recorder:
  db_url: sqlite:////config/home-assistant_v2.db
  purge_interval: 2
  purge_keep_days: 7

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - songpal
    - samsung_tv
    - harmony
    
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Telegram bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 543927188 # Oskar
      - 535882719 # Bella

# Notify
notify:
 - platform: telegram
   name: telegram_oskar
   chat_id: 543927188
   
 - platform: telegram
   name: telegram_bella
   chat_id: 535882719
  
 - platform: group  
   name: adults
   services:
     - service: telegram_oskar
     - service: telegram_bella

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret http_password

# Text to speech
tts:
  - platform: google
    language: sv
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Google Kalender
#google:
#  client_id: !secret client_id
#  client_secret: !secret client_secret

# Mitt ifttt
ifttt:
  key: !secret ifttt_key
  
# Floorplan
#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include floorplan.yaml

  
# Z-Wave support
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret network_key


input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
device_tracker: !include device_trackers.yaml
scene: !include scenes.yaml
automation old: !include automations.old.yaml
sensor: !include sensors.yaml
camera: !include camera.yaml
binary_sensor: !include binary_sensor.yaml
rest_command: !include rest_command.yaml
switch: !include switch.yaml
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml