homeassistant:
  # Name of the location where Home Assistant is running
  name: Hem
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 10
  unit_system: metric
  time_zone: Europe/Stockholm
# EXTERNAL DIRS
  whitelist_external_dirs:
  - /config/snapshot


  packages: !include_dir_named components/packages
alarm_control_panel: !include alarm.yaml
