
resources:
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/monster-card/monster-card.js
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/slideshow-card/slideshow-card.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /customcards/custom-lovelace/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /community_plugin/tracker-card/tracker-card.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /community_plugin/krisinfo-card/krisinfo-card.js
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /local/custom-lovelace/pollenkoll-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/surveillance-card/surveillance-card.js
    type: module
  - url: /community_plugin/lovelace-flower-card/flower-card.js
    type: module
  - url: /community_plugin/spotify-card/spotify-card.js
    type: module
  - url: /community_plugin/lovelace-google-keep-card/google-keep-card.js
    type: module
title: Kernehed Manison
views:
  - !include lovelace/home.yaml
  - !include lovelace/kitchen.yaml
  - !include lovelace/livingroom.yaml
  - !include lovelace/hallway.yaml
  - !include lovelace/basement.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/bathroom.yaml
  - !include lovelace/theus_room.yaml
  - !include lovelace/evenice_room.yaml
  - !include lovelace/system_network.yaml
  - !include lovelace/information.yaml
  - !include lovelace/media.yaml
  - !include lovelace/chromecasts.yaml
  - !include lovelace/flowers.yaml
#  - !include lovelace/cameras.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/alarm.yaml













