resources:
  - url: /customcards/custom-lovelace/text-element.js
    type: js
  - url: /customcards/custom-lovelace/monster-card.js
    type: js
  - url: /local/custom-lovelace/mini-media-player-bundle.js
    type: module
  - url: /local/custom-lovelace/slideshow-card.js?=1.1.0
    type: js
  - url: /customcards/custom-lovelace/fold-entity-row.js
    type: js
  - url: /customcards/custom-lovelace/swipe-card/swipe-card.js
    type: module
  - url: /customcards/custom-lovelace/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /customcards/custom-lovelace/tracker-card.js
    type: js
  - url: /customcards/custom-lovelace/card-tools.js
    type: js
  - url: /customcards/custom-lovelace/krisinfo.js
    type: js
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /local/custom-lovelace/pollenkoll-card.js
    type: js
  - url: /local/custom-lovelace/mini-graph-card-bundle.js?v=0.3.3
    type: module

title: Kernehed Manison
views:
  - !include lovelace/home.yaml
  - !include lovelace/kitchen.yaml
  - !include lovelace/livingroom.yaml
  - !include lovelace/hallway.yaml
  - !include lovelace/basement.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/bathroom.yaml
  - !include lovelace/theus_room.yaml
  - !include lovelace/evenice_room.yaml
  - !include lovelace/system_network.yaml
  - !include lovelace/information.yaml
  - !include lovelace/media.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/alarm.yaml













