custom_header:
  compact_mode: true
resources:
  - url: /hacsfiles/text-element/text-element.js
    type: js
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player.js
    type: module
  - url: /hacsfiles/slideshow-card/slideshow-card.js
    type: js
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /customcards/custom-lovelace/swipe-card/swipe-card.js
    type: module
  - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /hacsfiles/tracker-card/tracker-card.js
    type: js
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: js
  - url: /hacsfiles/krisinfo-card/krisinfo-card.js
    type: js
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /local/custom-lovelace/pollenkoll-card.js
    type: js
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/surveillance-card/surveillance-card.js
    type: module
  - url: /hacsfiles/lovelace-flower-card/flower-card.js
    type: module
  - url: /hacsfiles/spotify-card/spotify-card.js
    type: module
  - url: /hacsfiles/lovelace-google-keep-card/google-keep-card.js
    type: module
  - url: /hacsfiles/calendar-card/calendar-card.js
    type: js
title: Kernehed Manison
views:
  - !include lovelace/home.yaml
  - !include lovelace/kitchen.yaml
#  - !include lovelace/livingroom.yaml
  - !include lovelace/hallway.yaml
  - !include lovelace/basement.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/bathroom.yaml
  - !include lovelace/theus_room.yaml
  - !include lovelace/evenice_room.yaml
  - !include lovelace/system_network.yaml
  - !include lovelace/information.yaml
  - !include lovelace/media.yaml
  - !include lovelace/chromecasts.yaml
  - !include lovelace/flowers.yaml
#  - !include lovelace/cameras.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/alarm.yaml
  - !include lovelace/floorplan.yaml













