alias: Kamera motion
id: kamera_motion
initial_state: 'on'
trigger: 
  - platform: state
    entity_id: binary_sensor.entre_motion_eye
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: group.devices_adults
      state: 'not_home'
    - condition: time
      before: "06:00:00"
      after: "20:15:00"
action:
  - service: script.turn_on
    entity_id: script.entre_camera_snapshot #Snapshot 1
  - delay: '00:00:02'
  - service: script.turn_on
    entity_id: script.entre_camera_snapshot #Snapshot 2
  - delay: '00:00:02'
  - service: script.turn_on
    entity_id: script.entre_camera_snapshot #Snapshot 3
  - delay: '00:00:02'
  - service: script.turn_on
    entity_id: script.entre_camera_snapshot #Snapshot 4
  - delay: '00:00:02'
  - service: script.turn_on
    entity_id: script.entre_camera_snapshot #Snapshot 5
  - delay: '00:00:04'
  - service: notify.adults
    data:
      message: !secret camera_url_ingress
  - service: image_processing.scan
    entity_id: image_processing.deepstack_object_entre