alias: Kamera motion face detection
id: kamera_motion_face
initial_state: 'on'
trigger: 
  - platform: state
    entity_id: binary_sensor.entre_motion_eye
    to: 'on'
action:
  - delay: '00:00:05'
  - service: image_processing.scan
    entity_id: image_processing.face_counter_entre
  - delay: '00:00:11'
  - service: image_processing.scan
    entity_id: image_processing.face_counter_entre