id: morning_kettle_id 
alias: Vattenkokaren morgon
initial_state: 'on'
trigger: 
  platform: state 
  entity_id: sensor.oskars_bt_mqtt 
  to: Köket
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.devices_adults
      state: 'home'
    - condition: time
      after: '05:45:00'
      before: '07:00:00'
    - condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.vattenkokaren_morgon.attributes.last_triggered) | int > 3600 }}'
action:
  - service: script.speech_engine
    data_template:
      value1: >-
          {{ [
             "Godmorgon! Vattenkokaren är nu påslagen, ditt te kommer serveras rykande varmt. Stänger av den om 20 minuter för säkerhetsskull!",
             "Godmorgon! Vattenkokaren är nu påslagen och kommer värma ditt vatten. Du får dock hämta det själv. Stänger av den om 20 minuter för säkerhetsskull!!",
          ] | random }}
  - service: switch.turn_on
    entity_id: switch.fibaro_system_fgwpe_f_wall_plug_switch
  - delay:
      minutes: 20
  - service: switch.turn_off
    entity_id: switch.fibaro_system_fgwpe_f_wall_plug_switch
  
