alias: Återhämtningsmusik
initial_state: 'on'
trigger: 
  - platform: time
    at: "18:00:00"
action:
  - service: media_player.volume_set
    entity_id:
    - media_player.tts
    data:
      volume_level: 0.2
  - service: media_player.play_media
    data:
      entity_id:
        - media_player.tts
      media_content_id: !secret random_music
      media_content_type: 'music'
