id: good_night_id
alias: sleep_mode_on
initial_state: 'on'
trigger: 
  platform: state 
  entity_id: sensor.oskars_bt_mqtt 
  to: Sovrummet
  for: '00:05:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: person.oskar
      state: 'home'
    - condition: time
      after: '20:00:00'
      before: '04:00:00'
    - condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.sleep_mode_on.attributes.last_triggered) | int > 28800 }}'
action:
  - service: rest_command.sleep_mode
