id: alarm_is_not_armed_command
alias: 'alarm_is_not_armed_command'
trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    command: '/alarm_arm_away'
action:
- service: alarm_control_panel.alarm_arm_away
  data:
    entity_id:
      - alarm_control_panel.house
- service: telegram_bot.send_message
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    target: -1001200237113
    message: 'Okej, {{ trigger.event.data["from_first"] }} har nu larmat bortaläget.'
- service: telegram_bot.edit_replymarkup
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: -1001200237113
    inline_keyboard: 