id: 'disarm_alarm_command'
alias: 'disarm_alarm_command'
trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    command: '/disarm_alarm'
action:
- service: alarm_control_panel.alarm_disarm
  data:
    entity_id:
      - alarm_control_panel.house
- service: telegram_bot.send_message
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    target: -1001200237113
    parse_mode: markdown
    message: 'Okej, *{{ trigger.event.data["from_first"] }}* har nu larmat av huset.'
- service: telegram_bot.edit_replymarkup
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: -1001200237113
    inline_keyboard: 