id: 'milla_dog_food_yes_command'
alias: 'milla_dog_food_yes_command'
trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    command: '/milla_food_yes'
action:
- service: telegram_bot.send_message
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    target: -1001200237113
    message: 'Okej, {{ trigger.event.data["from_first"] }} fixar det.'
- service: telegram_bot.edit_replymarkup
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: -1001200237113
    inline_keyboard: 
- service: tts.google_translate_say
  entity_id: media_player.tts
  data:
   message: 'Okej, jag ser att någon har sett informationen!'