alias: Eves bokinlämning
initial_state: 'on'
trigger: 
  - platform: time
    at: "06:40:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.devices_adults
      state: 'home'
    - condition: time
      weekday:
      - wed
action:
  - service: tts.google_say
    entity_id: media_player.entre_speaker
    data:
     message: "PÅMINNELSE! Kom ihåg boken och simkläder!"