alias: Eves gymnastik
initial_state: 'on'
trigger: 
  - platform: time
    at: "06:40:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.devices_adults
      state: 'home'
    - condition: time
      weekday:
      - mon
action:
  - service: tts.google_translate_say
    entity_id: media_player.hallen
    data:
     message: "PÅMINNELSE! Kom ihåg gymnastikkläderna!"