alias: Radio weekdays
initial_state: 'off'
trigger: 
  - platform: time
    at: "06:00:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.devices_adults
      state: 'home'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - delay: '00:00:30'
  - service: media_player.volume_set
    entity_id:
    - media_player.entre_speaker
    - media_player.kitchen_speaker
    data:
      volume_level: 0.15
  - service: media_player.play_media
    data:
      entity_id:
        - media_player.entre_speaker
        - media_player.kitchen_speaker
      media_content_id: !secret content_silence_mp3
      media_content_type: music
  - service: tts.google_translate_say
    entity_id: media_player.entre_speaker
    data:
     message: Godmorgon, hoppas ni får en trevlig dag.
  - delay: '00:00:05'       
  - service: script.radio_p3
    entity_id: script.radio_p3