alias: Milla mat
initial_state: 'on'
trigger: 
  - platform: time
    at: "06:30:00"
condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
action:
  - service: media_player.volume_set
    entity_id:
    - media_player.tts
    data:
      volume_level: 0.5
  - service: media_player.play_media
    data:
      entity_id:
        - media_player.tts
      media_content_id: !secret content_silence_mp3
      media_content_type: music
  - service: tts.google_translate_say
    entity_id: media_player.tts
    data:
     message: 'Notera! Kom ih책g att Milla ska ha mat snart!'
  - service: telegram_bot.send_message
    data_template:
      target: -1001200237113
      message: 'Har milla f책tt mat, det 채r dags nu?'
      inline_keyboard:
        - "Fixar det:/milla_food_yes"
        - "Redan f책tt:/milla_food_no"
        - "Ignorera:/removekeyboard"