alias: "New device connected"
trigger:
  - platform: event
    event_type: device_tracker_new_device

action:
  - wait_template: >-
      {{ not is_state('media_player.tts', 'playing') }}

  - service: script.speech_engine
    data_template:
      NewDevice: "Det hittades en ny enhet p책 n채tverket.  Var s채ker p책 att kategorisera {{trigger.event.data.host_name}} inom cirkeln."