alias: 'responsibilities'

trigger:
  - platform: state
    entity_id: input_boolean.responsibilities
    to: 'on'

action:
  - service: script.speech_engine
    data:
      call_responsibilities: 1
      call_evenice_skola: 1