alias: 'tts storhagensförskola mat'
initial_state: 'on'
trigger:
  - platform: time
    at: '06:45:00'
action:
  - service: media_player.volume_set
    entity_id: media_player.entre_speaker
    data:
      volume_level: 0.2
  - service: tts.google_say
    entity_id: media_player.entre_speaker
    data_template:
      message: >-
        "På förskolan idag får Theus äta"
        {% if now().weekday() == 0 %}
          {{ states('sensor.storhagensforskola_lunch_mandag') }}
        {% elif now().weekday() == 1 %}
          {{ states('sensor.storhagensforskola_lunch_tisdag') }}
        {% elif now().weekday() == 2 %}
          {{ states('sensor.storhagensforskola_lunch_onsdag') }}
        {% elif now().weekday() == 3 %}
          {{ states('sensor.storhagensforskola_lunch_torsdag') }}
        {% elif now().weekday() == 4 %}
          {{ states('sensor.storhagensforskola_lunch_fredag') }}  
        {% endif %}
      cache: false