alias: 'tts storhagensförskola mat'
initial_state: 'on'
trigger:
  - platform: time
    at: '06:45:00'
condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: script.speech_engine
    data_template:
      value1: >-
        "På förskolan idag får Theus äta"
        {% if now().weekday() == 0 %}
          {{ states('sensor.storhagensforskola_lunch_mandag') }}
        {% elif now().weekday() == 1 %}
          {{ states('sensor.storhagensforskola_lunch_tisdag') }}
        {% elif now().weekday() == 2 %}
          {{ states('sensor.storhagensforskola_lunch_onsdag') }}
        {% elif now().weekday() == 3 %}
          {{ states('sensor.storhagensforskola_lunch_torsdag') }}
        {% elif now().weekday() == 4 %}
          {{ states('sensor.storhagensforskola_lunch_fredag') }}  
        {% endif %}
      call_inspirational_quote: 1
