alias: People Greeting 2
initial_state: 'on'
trigger:
  - platform: state
    entity_id:
      - device_tracker.ingelas_iphone
      - device_tracker.andreass_iphone
      - device_tracker.matildas_iphone
      - device_tracker.daniels_iphone
    from: 'not_home'
    to: 'home'
    for: '00:02:00'
condition:
  condition: time
  after: '07:00:00'
  before: '19:00:00'
action:
  - wait_template: >-
     {{ states.binary_sensor.front_door_sensor.state == 'on' }}
    timeout: '00:05:00'
    continue_on_timeout: 'false'
  - delay: '00:00:30'
  - service: script.speech_engine
    data_template:
      personarriving_guests: >-
       {%- if trigger.entity_id == 'device_tracker.matildas_iphone' -%}
         {%- set person = "Matilda" -%}
       {%- elif trigger.entity_id == 'device_tracker.ingelas_iphone' -%}
         {%- set person = "Ingela" -%}
       {%- elif trigger.entity_id == 'device_tracker.daniels_iphone' -%}
         {%- set person = "Daniel" -%}
       {%- elif trigger.entity_id == 'device_tracker.andreass_iphone' -%}
         {%- set person = "Andreas" -%}
       {%- else -%}
         {%- set person = "Alla" -%}
       {%- endif -%}    
        {%- macro greeting_sentence(person) -%}
          {{ [
             "Välkommen hem till oss" ~ person,
             "Men se här vad katten har släpat in?"  ~ person +" är här!",
             person + " är nu hos familjen Kernehed.",
             "Välkommen hem till oss "  ~ person + ".  Vi har saknat dig, eller åtminstone jag, Milla!",
             "Hos oss kan du känna dig som hemma, välkommen hit " ~ person,
             "Hej där "  ~ person +" Välkommen till vårat hem!",
             person ~ "! Välkommen hem till oss",
             "Jag vet en hemlighet! "  ~ person +" är här!",
             "Hej "  ~ person +" du har blivit hittad av det smartaste huset på gatan!",
             person + " är nu här.  Välkommen till Kernehed Mansion, mi casa su casa."
          ] | random }}
        {%- endmacro -%}
        {{- greeting_sentence(person) -}}
      call_inspirational_quote: 1