alias: '[Alarm] Disarmed'
id: alarm_disarmed
initial_state: 'on'
trigger:
  platform: state
  entity_id: alarm_control_panel.kernehed_manison
  to: disarmed
action:
  - service: media_player.volume_set
    entity_id: media_player.whole_house
    data:
      volume_level: '0.2'
  - service: notify.adults    
    data:
      message: Larmet har avaktiverats
  - service: tts.google_say
    entity_id: media_player.entre_speaker
    data:
      message: Larmet har avaktiverats.
  - service: script.turn_off
    entity_id: script.flash_lights
  - service: script.turn_off
    entity_id: script.light_loop

