alias: '[Alarm] Away Mode Armed'
id: alarm_armed_away
initial_state: 'on'
trigger:
  platform: state
  entity_id: alarm_control_panel.kernehed_manison
  to: 'armed_away'
action:
  - service: tts.google_translate_say
    entity_id: media_player.entre_speaker
    data:
      message: Larmet har aktiverats som borta läge. Hejdå.
  - service: media_player.volume_set
    entity_id: media_player.whole_house
    data:
      volume_level: '0.2'
  - delay: '00:00:05'
  - service: lock.lock
    entity_id: lock.polycontrol_danalock_v3_btze_locked
  - service: notify.adults
    data:
      message: Bortaläget aktiverat.
