alias: '[Alarm] Triggered'
initial_state: 'on'
id: alarm_triggered
trigger:
  - platform: state
    entity_id: alarm_control_panel.kernehed_manison
    to: triggered
action:
  - service: script.turn_on
    entity_id: script.flash_lights
  - service: media_player.volume_set
    entity_id: media_player.entre_speaker
    data:
      volume_level: '0.5'
  - service: media_player.play_media
    entity_id: media_player.entre_speaker
    data:
      media_content_id: !secret content_alarm_mp3
      media_content_type: audio/mp3
  - service: notify.adults
    data:
      message: ALARM TRIGGERED!!! {{ states[states.alarm_control_panel.kernehed_manison.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.kernehed_manison.attributes.changed_by.split(".")[1]].name }}
