alias: '[Alarm] Triggered'
initial_state: 'on'
id: alarm_triggered
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: triggered
action:
  - service: script.turn_on
    entity_id: script.flash_lights
  - service: media_player.volume_set
    entity_id: media_player.entre_speaker
    data:
      volume_level: '0.5'
  - service: media_player.play_media
    entity_id: media_player.entre_speaker
    data:
      media_content_id: !secret content_alarm_mp3
      media_content_type: audio/mp3
  - service: notify.adults
    data:
      message: 'ALARM TRIGGERED!!!'
  - service: script.turn_on
    entity_id: script.alarm_snapshot
  - delay: '00:00:02'
  - service: notify.adults
    data:
      message: !secret camera_url_ingress