alias: '[Alarm] Warning'
initial_state: 'on'
id: alarm_warning
trigger:
  platform: state
  entity_id: alarm_control_panel.house
  to: warning
action:
  - service: media_player.volume_set
    entity_id: media_player.whole_house
    data:
      volume_level: '0.2'
  - service: tts.google_translate_say
    entity_id: media_player.hallen
    data:
      message: Hej, Larmet har utlösts. Var vänlig avaktivera!
  - service: notify.adults
    data:
      message: ALARM varning {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][  states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name }}


