alias: "Blixtnedslag"
id: "blixtnedslag"
trigger:
  platform: numeric_state
  entity_id: sensor.blixtar_lightning_counter
  above: 0
action:
  - service: notify.adults
    data:
      message: "Det slog precis ner en blixt {{ states.sensor.blixtar_lightning_distance.state }} kilometer ifrån oss."
  - service: script.speech_engine
    data_template:
      value1: "et slog precis ner en blixt {{ states.sensor.blixtar_lightning_distance.state }} kilometer ifrån oss. Försök att hålla er inomhus!."