alias: Evenice lämnar skolan
initial_state: 'on'
trigger:
  platform: zone
  event: leave
  zone: zone.skolan
  entity_id: person.evenice
action:
  - service: notify.adults
    data:
      message: "Evenice har lämnat skolan, är hon påväg hem?!"
  - service: tts.google_translate_say
    entity_id: media_player.tts
    data:
     message: "Evenice har lämnat skolan, är hon påväg hem?!"