alias: Update notification
initial_state: 'on'
id: 'Update notification'
trigger:
  platform: state
  entity_id: binary_sensor.updater
  from: 'off'
  to: 'on'
action:
  - service: notify.telegram_oskar
    data:
      title: "Ny update hassio"
      message: "Home Assistant  {{ state_attr('binary_sensor.updater', 'newest_version') }}  is now available."
