alias: p_rainbowglitter
initial_state: 'on'
trigger:
  platform: state
  entity_id: input_select.christmas_pattern
  to: "Rainbow Glitter"
action:
  - service: rest_command.pattern_rainbowglitter 
   