alias: 'aktier summering kl 1800'
initial_state: 'on'
trigger:
  - platform: time
    at: '18:00:00'
condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: script.speech_engine
    data_template:
      value1: "Summering av några av dina aktier idag
             {{states.sensor.castellum.attributes.name}}
               Utveckling {{states.sensor.castellum.attributes.changePercent}}% 
               Kurs {{states.sensor.castellum.state}}kr
             {{states.sensor.xact_hogutdelande_fond.attributes.name}}
               Utveckling {{states.sensor.xact_hogutdelande_fond.attributes.changePercent}}%
               Kurs {{states.sensor.xact_hogutdelande_fond.state}}kr"