alias: 'tts lillhagsskolan mat'
initial_state: 'on'
trigger:
  - platform: time
    at: '06:48:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.sommarlov
      state: 'off'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: script.speech_engine
    data_template:
      value1: >-
        "På skolan idag får barnen äta"
        {% if now().weekday() == 0 %}
          {{ states('sensor.lillhagsskolan_lunch_mandag') }}
        {% elif now().weekday() == 1 %}
          {{ states('sensor.lillhagsskolan_lunch_tisdag') }}
        {% elif now().weekday() == 2 %}
          {{ states('sensor.lillhagsskolan_lunch_onsdag') }}
        {% elif now().weekday() == 3 %}
          {{ states('sensor.lillhagsskolan_lunch_torsdag') }}
        {% elif now().weekday() == 4 %}
          {{ states('sensor.lillhagsskolan_lunch_fredag') }}  
        {% endif %}
      call_inspirational_quote: 1
      call_hamstermat: 1