alias: 'SMHI Alert'
initial_state: 'on'
trigger:
  - platform: time_pattern
    hours : '/3'
    minutes: 0
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: time
      after: '06:00:00'
      before: '20:00:00'
    - condition: state
      entity_id: sensor.smhialert
      state: 'Alert'
action:
  - service: notify.adults
    data_template:
      title: 'SMHI Varning'
      message: "{{ states.sensor.smhialert.attributes.messages['024']['msgs'][0]['event'] }}  {{ states.sensor.smhialert.attributes.messages['024']['msgs'][0]['description'] | regex_replace('Intensitet: |När:.*|Var:.*|Kommentar:.*', '') }}"
#  - service: script.speech_engine
#    data:
#      call_smhi_alert: 1
