alias: People Greeting
initial_state: 'on'
trigger:
  - platform: state
    entity_id:
      - person.bella
      - person.oskar
      - person.evenice
      - person.theus
    from: 'not_home'
    to: 'home'
condition:
  condition: time
  after: '07:00:00'
  before: '19:00:00'
action:
  - wait_template: >-
     {{ states.binary_sensor.front_door_sensor.state == 'on' }}
    timeout: '00:05:00'
    continue_on_timeout: 'false'
  - delay: '00:00:30'
  - service: script.speech_engine
    data_template:
      personarriving: >-
       {%- if trigger.entity_id == 'person.bella' -%}
         {%- set person = "Bella" -%}
       {%- elif trigger.entity_id == 'person.oskar' -%}
         {%- set person = "Oskar" -%}
       {%- elif trigger.entity_id == 'person.evenice' -%}
         {%- set person = "Evenice" -%}
       {%- elif trigger.entity_id == 'person.theus' -%}
         {%- set person = "Theus" -%}
       {%- else -%}
         {%- set person = "Alla" -%}
       {%- endif -%}
        {%- macro greeting_sentence(person) -%}
          {{ [
             "Välkommen hem " ~ person,
             "Gissa vem som kommit hem"  ~ person +" har",
             person + " är nu hemma.",
             "Välkommen hem "  ~ person +".  Vi har saknat dig, eller åtminstone Milla!",
             "I världen är du bara någon men för någon är du hela världen. Välkommen hem " ~ person,
             "Hej där " ~ person + " Välkommen hem",
             "Knack Knack. Vem där "  ~ person +" är",
             person ~ "! Du är hemma",
             "Jag vet en hemlighet! "  ~ person +" är hemma!",
             "Hej "  ~ person +" du har blivit hittad av det smartaste huset på gatan",
             person + " är nu här.  Hash tag Välkommen hem.",
             person + " är nu här.  Hash tag Hemma.",
             person + " är nu här.  Hash tag Smart hem.",
             person + " är nu här.  Välkommen till Kernehed Manison, mi casa su casa."
          ] | random }}
        {%- endmacro -%}
        {{greeting_sentence(person)}}
      call_responsibilities: 1
      call_inspirational_quote: 1
      call_fotbolls_traning: 1
      call_arsdag: 1