alias: 'Set startup theme'
initial_state: 'on'
trigger:
  - platform: homeassistant
    event: start
action:
  - service: frontend.set_theme
    data:
      name: darkydark
  - service: python_script.plant_problems