alias: Tänd bänkbelysningen när rörelse
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.banksensor
  to: 'on'
action:
  service: light.turn_on
  entity_id: light.koket_bank

