alias: Tänd badrumsbelysningen vid rörelse
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.badrumssensor
  to: 'on'
action:
  service: light.turn_on
  entity_id:
  - light.badrumslampa_1
  - light.badrumslampa_2