alias: Släck badrumsbelysningen efter 7 min vid sista rörelse
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.badrumssensor
  to: 'off'
  for:
    minutes: 7
action:
  service: light.turn_off
  entity_id:
  - light.badrumslampa_1
  - light.badrumslampa_2