# Turn lights on when sun is set if we are home.
alias: 'Light on when sun is down'
id: 'lights when sun is set'
initial_state: 'on'
trigger:
  platform: sun
  event: sunset
  offset: "-00:45:00"
condition:
  condition: state
  entity_id: group.devices_adults
  state: 'home'
action:
  - service: light.turn_on
    entity_id:
    - group.light_hallen
    - light.sovrum_spotlights
    - light.hall_trapp
  - service: switch.turn_on
    entity_id: switch.rest_julbelysning
  - service: script.speech_engine
    data:
      call_dark_outside: 1