  ##############################################
  ####  Tänd kl 06.00 på veckorna [Lights]  ####
  ##############################################   
alias: Tänd lamporna vid 06.00
initial_state: 'on'
trigger: 
  - platform: time
    at: "06:00:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.devices_adults
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: light.turn_on
    entity_id: light.hall_1
  - service: light.turn_on
    entity_id: light.hall_2
  - service: light.turn_on
    entity_id: group.light_hallen
  - service: light.turn_on
    data:
      entity_id: light.sovrum_spotlights
      brightness: 30