alias: Tänd bänkbelysningen vid rörelse
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.altan_motion_sensor
  to: 'on'
action:
  service: light.turn_on
  entity_id:
  - light.altan_lampa