alias: Tänd tvättstuge lamporna när rörelse
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.tvattstugan_motion_sensor
  to: 'on'
action:
  service: light.turn_on
  entity_id: group.light_tvattstugan

