alias: Släck bänkbelysningen efter 10 min när sista rörelse
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.banksensor
  to: 'off'
  for:
    minutes: 4
action:
  service: light.turn_off
  entity_id: light.koket_bank 