# Turn lights on when sun is set if we are home.
alias: 'Light on when sun is down'
id: 'lights when sun is set'
initial_state: 'on'
trigger:
  platform: state
  entity_id:
   - device_tracker.evenice_iphone
   - group.bella_devices
   - device_tracker.oskarstelefon
  to: 'home'
condition:
  condition: sun
  after: sunset
  after_offset: "-01:30:00"
action:
  - service: light.turn_on
    entity_id:
    - group.light_hallen
    - light.vardagsrum_spotlights
    - light.vardagsrum_trapp
  - service: script.speech_engine
    data:
      call_dark_outside: 1