alias: Sommarlov
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: '/6'
    
condition:
  - condition: state
    entity_id: calendar.sommarlov
    state: 'on'

action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.sommarlov