alias: 'Update Plant Problems'
trigger:
  - platform: state
    entity_id: 
    - plant.flower_1
    - plant.flower_2
    - plant.flower_3
    - plant.flower_4
    - plant.flower_5
    - plant.flower_6
    - plant.flower_7
    - plant.flower_8
action:
  - service: python_script.plant_problems
  - service: script.speech_engine
    data:
      call_plants: 1