alias: "Robot: Robot stopped cleaning"
initial_state: "on"
trigger:
  - platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    from: "returning"
    to: "docked"
action:
  - service: notify.adults
    data:
      title: "Robot"
      message: "Städning slutförd efter {{states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time}} minuter."
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.cleaned_today