alias: "Robot: Reset cleaned today counter"
initial_state: "on"
trigger:
  - platform: time
    at: "01:00:00"
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.cleaned_today