alias: "Robot: Robot cleanup if nobody is home"
initial_state: "on"
trigger:
  - platform: time
    at: "10:00"
  - platform: state
    entity_id: group.devices_adults
    from: home
    to: not_home
condition:
  condition: and
  conditions:
    - condition: time
      after: "10:00:00"
      before: "22:00:00"
      weekday:
       - mon
       - wed
       - fri
       - sun
    - condition: state
      entity_id: group.devices_adults
      state: not_home
    - condition: state
      entity_id: input_boolean.cleaned_today
      state: "off"
    - condition: state
      entity_id: input_boolean.semester
      state: "off"
action:
  - service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner