alias: "Robot: Robot started cleaning"
initial_state: "on"
trigger:
  - platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    from: "docked"
    to: "cleaning"
action:
  - service: notify.adults
    data:
      title: "Robot"
      message: "Nemo har börjat städa!"
