alias: Dorrklockan Halloween
id: dorrklockan halloween
initial_state: 'off'
trigger: 
  - platform: state
    entity_id: binary_sensor.dorrklockan
    to: 'off'
action:
  - service: switch.turn_off
    entity_id: switch.rest_julbelysning
  - service: light.turn_off
    entity_id: 
    - group.theus_rum
    - group.light_hallen
    - light.vardagsrum_trapp
  - service: media_player.volume_set
    entity_id:
    - media_player.hallen
    data:
      volume_level: 0.8
  - service: media_player.play_media
    data:
      entity_id:
        - media_player.hallen
      media_content_id: !secret content_halloween_mp3
      media_content_type: music
  - service: script.turn_on
    entity_id: script.dorrklockan_snapshot #Snapshot 1
  - delay: '00:00:02'
  - service: script.turn_on
    entity_id: script.dorrklockan_snapshot #Snapshot 2
  - service: script.turn_on
    entity_id: script.dorrklockan_snapshot #Snapshot 3
  - delay: '00:00:02'
  - service: script.turn_on
    entity_id: script.dorrklockan_snapshot #Snapshot 4
  - delay: '00:00:29'
  - service: light.turn_on
    entity_id:
    - group.theus_rum
    - group.light_hallen
    - light.vardagsrum_trapp
  - service: switch.turn_on
    entity_id: switch.rest_julbelysning