alias: Dorrklockan 
id: dorrklockan
initial_state: 'on'
trigger: 
  - platform: state
    entity_id: binary_sensor.dorrklockan
    to: 'off'
action:
  - service: tts.google_translate_say
    entity_id: media_player.tts
    data:
     message: 'Någon ringer på dörren!'
  - service: tts.google_translate_say
    entity_id: media_player.kallare_mini
    data:
     message: 'Någon ringer på dörren!'
  - service: script.turn_on
    entity_id: script.dorrklockan_snapshot #Snapshot 1
  - delay: '00:00:02'
  - service: script.turn_on
    entity_id: script.dorrklockan_snapshot #Snapshot 2
  - delay: '00:00:02'
  - service: notify.adults
    data:
      message: !secret camera_url_ingress
  - service: telegram_bot.send_message
    data_template:
      target: -1001200237113
      message: 'Någon ringer på dörren, kan du öppna?'
      inline_keyboard:
        - "Öppnar:/dorrklockan_yes"
        - "Upptagen:/dorrklockan_no"
        - "Ta bort tangentbordet:/removekeyboard"