alias: Bella hemma
initial_state: 'on'
trigger:
  platform: zone
  event: enter
  zone: zone.home
  entity_id: person.bella
action:
  - service: notify.telegram_oskar
    data:
      message: "Bella har kommit hem!"


