alias: Bella hemma
initial_state: 'on'
trigger:
  platform: zone
  event: enter
  zone: zone.home
  entity_id: device_tracker.google_maps_103719873476746592925
action:
  - service: notify.telegram_oskar
    data:
      message: "Bella har kommit hem!"


