alias: Evenice hos mamma
initial_state: 'on'
trigger:
  platform: zone
  event: enter
  zone: zone.mamma
  entity_id: person.evenice
action:
  - service: notify.adults
    data:
      message: "Evenice är hos farmor!"
  - service: tts.google_translate_say
    entity_id: media_player.tts
    data:
      message: "Evenice är hos farmor!"