alias: Evenice hos mamma
initial_state: 'on'
trigger:
  platform: zone
  event: enter
  zone: zone.mamma
  entity_id: device_tracker.evenice_iphone
action:
  - service: notify.adults
    data:
      message: "Evenice är hos mamma!"
  - service: tts.google_translate_say
    entity_id: media_player.hallen
    data:
     message: "Evenice är hos mamma!"