alias: Evenice ej hemma
initial_state: 'on'
trigger:
  platform: zone
  event: leave
  zone: zone.home
  entity_id: person.evenice
action:
  - service: notify.adults
    data:
      message: "Evenice har g책tt hemifr책n!"
  - service: tts.google_translate_say
    entity_id: media_player.tts
    data:
     message: "Evenice har g책tt hemifr책n!"