alias: Evenice 채r hemma
initial_state: 'on'
trigger:
  platform: zone
  event: enter
  zone: zone.home
  entity_id: device_tracker.evenice_iphone
action:
  - service: notify.adults
    data:
      message: "Evenice 채r hemma eller v채ldigt n채ra!"