alias: Evenice i skolan
initial_state: 'on'
trigger:
  platform: zone
  event: enter
  zone: zone.skolan
  entity_id: device_tracker.evenice_iphone
action:
  - service: notify.adults
    data:
      message: "Evenice är i skolan!"
  - service: tts.google_translate_say
    entity_id: media_player.tts
    data:
     message: "Evenice är i skolan!"