alias: 'Krisinformation Alert'
id: krisinformation
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.krisinformation
  to: "Alert"
action:
  - service: notify.adults
    data_template:
      message: >
        {{states.sensor.krisinformation_stockholm.attributes.messages[0].Headline}} - {{states.sensor.krisinformation_stockholm.attributes.messages[0].Message}} {{states.sensor.krisinformation_stockholm.attributes.messages[0].Web}}