alias: 'light unavailable'
initial_state: 'on'
trigger:
  platform: state
  entity_id:
  - light.hall_1
  - light.hall_2
  - light.kallarspot_1
  - light.kallarspot_2
  - light.kallarspot_4
  - light.kallarspot_5
  - light.kallarspot_6
  - light.skafferiet
  - light.sovrummet_1
  - light.sovrummet_2
  - light.tvattstugan_1
  - light.tvattstugan_2
  - light.vardagsrum_stativ
  - light.vardagsrum_tak
  - light.vardagsrum_trapp
  - light.theus_lampa
  - light.evenice_lampa
  - light.badrumslampa_1
  - light.badrumslampa_2
  - light.altan_lampa
  to: unavailable
action:
  - service: notify.telegram_oskar
    data_template:
      title: 'Home Assistant'
      message: >
        {% if trigger.to_state.state | lower == "unavailable" %}
           {{ trigger.to_state.attributes.friendly_name }} är nu avstängd eller sönder, kolla!!
        {% else %}
           {{ trigger.to_state.attributes.friendly_name }} Detta gör ingenting men står här ändå
        {% endif %}