alias: Oskar ICA
initial_state: 'on'
trigger:
  platform: zone
  event: enter
  zone: zone.ica_fjallbacken
  entity_id: device_tracker.google_maps_114170795730412573739
action:
  - service: notify.adults
    data:
      message: "Oskar är vid ICA Fjällbacken, handla?"
  - service: tts.google_translate_say
    entity_id: media_player.tts
    data:
     message: "Oskar är vid ICA Fjällbacken, handla skynda hör av dig till honom?"