alias: Brandvarnare
id: 'brandvarnare'
initial_state: 'on'
trigger:
  platform: state
  entity_id: group.brandvarnare
  from: 'off'
  to: 'on'
action:
  - service: tts.google_say
    data:
      message: DET BRINNER, UTRYM!
  - service: notify.adults
    data:
      message: DET BRINNER, UTRYM!