esphome:
  name: esp32_flora_2
  platform: ESP32
  board: esp-wrover-kit

esp32_ble_tracker:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Flora 2 Fallback Hotspot"
    password: "8z27YIXssitu"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
