esphome:
  name: kallaren_esp32
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_beacon:
  type: iBeacon
  uuid: '52f29bcc-461d-3e35-88c0-2965ac904acd'
  
  
mqtt:
  broker: 192.168.1.203
  username: sparsnas
  password: Evenice2923!
  topic_prefix: kallaren/topic
  birth_message:
    topic: kallaren/topic
    payload: online
  will_message:
    topic: kallaren/topic
    payload: offline


# Enable logging
logger:

# Enable Home Assistant API
ota:
