esphome:
  name: sovrummet_esp32
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
esp32_ble_beacon:
  type: iBeacon
  uuid: '53f3e878-383c-bbef-7542-34498a05b36f'

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
