esphome:
  name: test
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:



switch:
  - platform: gpio
    pin: GPIO26
    name: "Framåt"
    id: relay1
    interlock: [relay2]

  - platform: gpio
    pin: GPIO27
    name: "Bakåt"
    id: relay2
    interlock: [relay1]
    
  - platform: gpio
    pin: 14
    name: "enable"
    restore_mode: ALWAYS_ON