play_suggested:
  description: Play the suggested video from the specified program name
  fields:
    program_name:
      description: The name of the TV4 program
      example: "nyhetsmorgon"
    entity_id:
      description: Name(s) of entities to play on.
      example: "media_player.living_room_chromecast"
