title: Home
views:
  - title: iCloud3
    path: icloud3
    panel: true
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: glance
                entities:
                  - entity: device_tracker.gary_iphone
                    name: Gary
                  - entity: sensor.gary_iphone_interval
                    name: Interval
                  - entity: sensor.gary_iphone_zone_distance
                    name: Distance
                  - entity: sensor.gary_iphone_travel_time
                    name: TravTime
                  - entity: sensor.gary_iphone_next_update
                    name: NextUpdt
                  - entity: input_boolean.gary_driving_flag
                    name: DrivingFlag
                    tap_action:
                      action: toggle
                  - entity: sensor.gary_iphone_dir_of_travel
                    name: Direction
                  - entity: sensor.gary_iphone_travel_distance
                    name: TravDist
                  - entity: sensor.gary_iphone_last_located
                    name: Located
                  - entity: sensor.gary_iphone_last_update
                    name: LastUpdt
                state_color: true
                show_icon: false
                title: Gary
              - type: entities
                entities:
                  - entity: sensor.gary_iphone_info
                    name: Info - Gary
                    icon: 'mdi:information-outline'
              - type: glance
                entities:
                  - entity: device_tracker.lillian_iphone
                    name: Lillian
                  - entity: sensor.lillian_iphone_interval
                    name: Interval
                  - entity: sensor.lillian_iphone_zone_distance
                    name: Distance
                  - entity: sensor.lillian_iphone_travel_time
                    name: TravTime
                  - entity: sensor.lillian_iphone_next_update
                    name: NextUpdt
                  - entity: input_boolean.lillian_driving_flag
                    name: DrivingFlag
                    tap_action:
                      action: toggle
                  - entity: sensor.lillian_iphone_dir_of_travel
                    name: Direction
                  - entity: sensor.lillian_iphone_travel_distance
                    name: TravDist
                  - entity: sensor.lillian_iphone_last_located
                    name: Located
                  - entity: sensor.lillian_iphone_last_update
                    name: LastUpdt
                show_icon: false
                state_color: true
                title: Lillian
              - type: entities
                entities:
                  - entity: sensor.lillian_iphone_info
                    name: Info - Lillian
                    icon: 'mdi:information-outline'
              - type: entities
                entities:
                  - script.homeassistant_restart
          - type: 'custom:icloud3-event-log-card'
  - title: Map
    path: map
    badges: []
    cards:
      - type: map
        entities:
          - entity: device_tracker.gary_iphone
          - entity: device_tracker.lillian_iphone
        title: Map
        hours_to_show: 12
  - title: iC3-iphone
    path: ic3-iphone
    panel: false
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - entity: device_tracker.gary_iphone
                name: Gary
              - entity: sensor.gary_iphone_interval
                name: Interval
              - entity: sensor.gary_iphone_zone_distance
                name: Distance
              - entity: sensor.gary_iphone_travel_time
                name: TravTime
              - entity: sensor.gary_iphone_next_update
                name: NextUpdt
              - entity: sensor.gary_iphone_dir_of_travel
                name: Direction
              - entity: sensor.gary_iphone_last_located
                name: Located
              - entity: sensor.gary_iphone_last_update
                name: LastUpdt
            title: Gary
          - type: entities
            entities:
              - entity: sensor.gary_iphone_info
                name: Info
                icon: 'mdi:information-outline'
          - type: glance
            entities:
              - entity: device_tracker.lillian_iphone
                name: Lillian
              - entity: sensor.lillian_iphone_interval
                name: Interval
              - entity: sensor.lillian_iphone_zone_distance
                name: Distance
              - entity: sensor.lillian_iphone_travel_time
                name: TravTime
              - entity: sensor.lillian_iphone_next_update
                name: NextUpdt
              - entity: sensor.lillian_iphone_dir_of_travel
                name: Direction
              - entity: sensor.lillian_iphone_last_located
                name: Located
              - entity: sensor.lillian_iphone_last_update
                name: LastUpdt
            title: Lillian
          - type: entities
            entities:
              - entity: sensor.lillian_iphone_info
                name: Info
                icon: 'mdi:information-outline'
          - type: 'custom:icloud3-event-log-card'
  - badges: []
    cards:
      - type: 'custom:icloud3-event-log-card'
    icon: 'mdi:information-outline'
    path: icoud3-event-log
    title: iCoud3 Event Log